# Generated by Django 3.2.9 on 2021-11-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('genero', models.BooleanField(default=False, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('nit_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nit')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
